name: 'MA Java CI Coverage with Sonar'
description: 'MA Java build, test and analyze flow'
inputs:
  java-version:
    description: 'The Java version to set up. Takes a whole or semver Java version.'
    required: true
    default: '17'
  java-distribution:
    description: 'Java distribution.'
    required: true
    default: 'temurin'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distribution }}
        cache: gradle
        
    - name: Cache SonarCloud packages
      uses: actions/cache@v5
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Build and analyze
      shell: bash
      run: ./gradlew build sonar --info

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: gradle-test-reports
        path: '**/build/reports/tests/'
        if-no-files-found: ignore

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v5
      continue-on-error: true
