name: 'MA Node CI Lint'
description: 'A collection of common node jobs and cache operations'
inputs:
  node-version:
    description: 'The Node version to set up.'
    required: true
    default: 14
  yarn-command:
    description: 'Command to run that is defined in package.json'
    required: true
    default: lint
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@main
    - name: Cache node modules
      uses: actions/cache@main
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-cache-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-cache-node-modules-
          ${{ runner.os }}-
    - name: Install Dependencies
      uses: actions/setup-node@main
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
    - run: yarn install # will run `yarn install` command
      shell: bash
    - name: Lint
      run: yarn ${{ inputs.yarn-command }}
      shell: bash
